### ISSUE TITLE
what's the scaling module? 

### ISSUE THREAD

**Issue by Eipgen** [perone/Pyevolve#82]
**I want to use the Pyevolve in python3, and the I download the package follow the Pull request instruction _https://github.com/perone/Pyevolve/pull/79_  then I find the bug, what can I do ?**
>Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from pyevolve import __version__, __author__
  File "/mnt/e/sub/Pyevolve-master/Pyevolve-master/pyevolve/__init__.py", line 22, in <module>
    import pyevolve.Consts
  File "/mnt/e/sub/Pyevolve-master/Pyevolve-master/pyevolve/Consts.py", line 369, in <module>
    import Scaling
ModuleNotFoundError: No `module` named 'Scaling`

**Comment by perone** [comment]
This repo **is not outdated**, it just don't have support for Python 3 and nobody contributed with a pull-request containing a testing suite. But you're always free to contribute.
